# Generated by Django 3.2 on 2021-04-28 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uzytkownicy',
            fields=[
                ('identyfikator', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('haslo', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Uzytkownik',
                'verbose_name_plural': 'Uzytkownicy',
            },
        ),
        migrations.CreateModel(
            name='Zadania',
            fields=[
                ('identyfikator', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=20)),
                ('trudnosc', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Zadanie',
                'verbose_name_plural': 'Zadania',
            },
        ),
        migrations.CreateModel(
            name='Wysylki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('poprawne_testy', models.IntegerField()),
                ('wszystkie_testy', models.IntegerField()),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tester.uzytkownicy')),
                ('zadanie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tester.zadania')),
            ],
            options={
                'verbose_name': 'Wysyłka',
                'verbose_name_plural': 'Wysyłki',
            },
        ),
    ]
