# Generated by Django 3.2 on 2021-04-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tester', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zadania',
            name='adres',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
