# Generated by Django 3.2 on 2021-04-28 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tester', '0002_zadania_adres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wysylki',
            name='wszystkie_testy',
        ),
    ]
