# Generated by Django 3.2 on 2021-04-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tester', '0003_remove_wysylki_wszystkie_testy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zadania',
            name='adres',
        ),
        migrations.AddField(
            model_name='wysylki',
            name='raport',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
