# Generated by Django 3.2 on 2021-04-29 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tester', '0004_auto_20210429_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wysylki',
            name='poprawne_testy',
        ),
    ]
