# Generated by Django 3.2 on 2021-04-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tester', '0005_remove_wysylki_poprawne_testy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wysylki',
            name='data',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='wysylki',
            name='raport',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
