# Generated by Django 3.2 on 2021-04-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tester', '0006_auto_20210429_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wysylki',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
