# Generated by Django 3.2 on 2021-04-29 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tester', '0007_alter_wysylki_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wysylki',
            name='data',
        ),
    ]
