# Generated by Django 3.2 on 2021-04-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tester', '0008_remove_wysylki_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='wysylki',
            name='data',
            field=models.DateTimeField(null=True),
        ),
    ]
